--TOP (Limit)
Restrive the no of colmn and rows

Syntax

SELECT TOP 3
* FROM TABLE;

EXAMPLE-
Retrive only 3 customer
SELECT TOP 3 * FROM TABLE;

--EXAMPLE 2
--RETRIVE ALL THE TOP 3 CUSTOMER WITH HIGH SCORE
SELECT TOP 3 *
FROM CUSTOMER
ORDER BY Score DESC;
